# ============================================================
# DEPLOYMENT — frontend
# Tells Kubernetes how to run the frontend app.
# Uses nginx:alpine as a simple hello-world web server.
# In real life this would be your Next.js Docker image.
#
# image: 366554472163.dkr.ecr.ap-northeast-3.amazonaws.com/kaniko-frontend:68
# What it does: serves a simple HTML page on port 80
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lab
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      serviceAccountName: frontend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
        - name: frontend
          image: 366554472163.dkr.ecr.ap-northeast-3.amazonaws.com/kaniko-frontend:68
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: frontend-config
          env:
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: APP_SECRET_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: lab
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
