# ============================================================
# DEPLOYMENT — api
# The API service returns JSON dummy data to the frontend.
# Uses hashicorp/http-echo — a tiny Go server that returns
# a custom message as JSON. Perfect for lab testing.
#
# image: 366554472163.dkr.ecr.ap-northeast-3.amazonaws.com/kaniko-api:69
# What it does: returns a JSON response on any HTTP request
# Test it: curl http://api-svc:8080
# ============================================================
# ============================================================
# DEPLOYMENT — api
# image: 366554472163.dkr.ecr.ap-northeast-3.amazonaws.com/kaniko-api:69
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lab
  labels:
    app: api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      serviceAccountName: api-sa
      containers:
        - name: api
          image: 366554472163.dkr.ecr.ap-northeast-3.amazonaws.com/kaniko-api:69
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20 
